apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: hm-adminregister
  namespace: teamdigihot
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: teamdigihot
  secretName: hm-adminreg-unleash-secret
  environment: {{unleash_environment}}
