/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/admreg/admin/api/v1/agreement/delkontrakt/registrations": {
    post: operations["createDelkontrakt"];
  };
  "/admreg/admin/api/v1/agreement/delkontrakt/registrations/agreement/{agreementId}": {
    get: operations["findByAgreementId"];
  };
  "/admreg/admin/api/v1/agreement/delkontrakt/registrations/{id}": {
    get: operations["findByDelkontraktId"];
    put: operations["updateDelkontrakt"];
    delete: operations["deleteDelkontraktById"];
  };
  "/admreg/admin/api/v1/agreement/registrations": {
    get: operations["findAgreements"];
    post: operations["createAgreement"];
  };
  "/admreg/admin/api/v1/agreement/registrations/draft/from/{id}/reference/{reference}": {
    post: operations["createAgreementFromAnother"];
  };
  "/admreg/admin/api/v1/agreement/registrations/draft/reference": {
    post: operations["draftAgreementWith"];
  };
  "/admreg/admin/api/v1/agreement/registrations/draft/reference/{reference}": {
    post: operations["draftAgreement"];
  };
  "/admreg/admin/api/v1/agreement/registrations/{id}": {
    get: operations["getAgreementById"];
    put: operations["updateAgreement"];
    delete: operations["deleteAgreement"];
  };
  "/admreg/admin/api/v1/agreement/registrations/{id}/delkontrakt/{delkontraktId}": {
    get: operations["getDelkontraktById"];
    delete: operations["deleteDelkontraktById_1"];
  };
  "/admreg/admin/api/v1/bestillingsordning/registrations": {
    post: operations["createBestillingsordning"];
  };
  "/admreg/admin/api/v1/bestillingsordning/registrations/{hmsArtNr}": {
    get: operations["findByHmsNr"];
    put: operations["updateBestillingsordningStatus"];
  };
  "/admreg/admin/api/v1/import/token/{supplierId}": {
    post: operations["createSupplierToken"];
  };
  "/admreg/admin/api/v1/isocategory/registrations": {
    get: operations["getAllCategories"];
    post: operations["createIsoCategory"];
  };
  "/admreg/admin/api/v1/isocategory/registrations/{isocode}": {
    get: operations["getCategoryByIsocode"];
    put: operations["updateCategoryByIsocode"];
  };
  "/admreg/admin/api/v1/media/agreement/files/{oid}": {
    post: operations["uploadAgreementFiles"];
  };
  "/admreg/admin/api/v1/media/product/files/{oid}": {
    post: operations["uploadProductFiles"];
  };
  "/admreg/admin/api/v1/media/{oid}": {
    get: operations["getMediaList"];
  };
  "/admreg/admin/api/v1/media/{oid}/{uri}": {
    delete: operations["deleteFile"];
  };
  "/admreg/admin/api/v1/news": {
    get: operations["getNews"];
    post: operations["createNews"];
  };
  "/admreg/admin/api/v1/news/draft": {
    post: operations["createNewsDraft"];
  };
  "/admreg/admin/api/v1/news/{id}": {
    put: operations["updateNews"];
    delete: operations["deleteNews"];
  };
  "/admreg/admin/api/v1/product-agreement": {
    post: operations["createProductAgreement"];
  };
  "/admreg/admin/api/v1/product-agreement/batch": {
    put: operations["updateProductAgreements"];
    post: operations["createProductAgreements"];
  };
  "/admreg/admin/api/v1/product-agreement/excel-import": {
    post: operations["excelImport"];
  };
  "/admreg/admin/api/v1/product-agreement/get-by-ids": {
    post: operations["getProductsAgreementsByIds"];
  };
  "/admreg/admin/api/v1/product-agreement/ids": {
    delete: operations["deleteProductAgreementByIds"];
  };
  "/admreg/admin/api/v1/product-agreement/variants/delkontrakt/{id}": {
    get: operations["getProductVariantsByDelkontraktId"];
  };
  "/admreg/admin/api/v1/product-agreement/variants/{id}": {
    get: operations["getProductVariantsByAgreementId"];
  };
  "/admreg/admin/api/v1/product-agreement/{id}": {
    get: operations["getProductsByAgreementId"];
    delete: operations["deleteProductAgreementById"];
  };
  "/admreg/admin/api/v1/product/registrations": {
    get: operations["findProducts"];
    post: operations["createProduct"];
  };
  "/admreg/admin/api/v1/product/registrations/approve/{id}": {
    put: operations["approveProduct"];
  };
  "/admreg/admin/api/v1/product/registrations/draft/supplier/{supplierId}": {
    post: operations["draftProduct"];
  };
  "/admreg/admin/api/v1/product/registrations/draft/variant/{id}": {
    post: operations["createProductVariant"];
  };
  "/admreg/admin/api/v1/product/registrations/draftWith/supplier/{supplierId}": {
    post: operations["draftProductWith"];
  };
  "/admreg/admin/api/v1/product/registrations/excel/export": {
    post: operations["createExport"];
  };
  "/admreg/admin/api/v1/product/registrations/excel/import": {
    post: operations["importExcel"];
  };
  "/admreg/admin/api/v1/product/registrations/excel/import-dryrun": {
    post: operations["importExcelDryrun"];
  };
  "/admreg/admin/api/v1/product/registrations/hmsArtNr/{hmsArtNr}": {
    get: operations["getProductByHmsArtNr"];
  };
  "/admreg/admin/api/v1/product/registrations/series/group": {
    get: operations["findSeriesGroup"];
  };
  "/admreg/admin/api/v1/product/registrations/series/{seriesId}": {
    get: operations["findBySeriesIdAndSupplierId"];
  };
  "/admreg/admin/api/v1/product/registrations/til-godkjenning": {
    get: operations["findProductsPendingApprove"];
  };
  "/admreg/admin/api/v1/product/registrations/{id}": {
    get: operations["getProductById"];
    put: operations["updateProduct"];
    delete: operations["deleteProduct"];
  };
  "/admreg/admin/api/v1/supplier/registrations": {
    get: operations["findSuppliers"];
    post: operations["createSupplier"];
  };
  "/admreg/admin/api/v1/supplier/registrations/{id}": {
    get: operations["getById"];
    put: operations["updateSupplier"];
    delete: operations["deactivateSupplier"];
  };
  "/admreg/admin/api/v1/techlabel/registrations": {
    get: operations["getAllTechLabels"];
    post: operations["createTechLabel"];
  };
  "/admreg/admin/api/v1/techlabel/registrations/{id}": {
    get: operations["getTechLabelById"];
    put: operations["updateTechLabel"];
  };
  "/admreg/admin/api/v1/users": {
    get: operations["getUsers"];
    post: operations["createUser"];
  };
  "/admreg/admin/api/v1/users/email/{email}": {
    get: operations["getUserByEmail"];
  };
  "/admreg/admin/api/v1/users/password": {
    put: operations["changePassword"];
  };
  "/admreg/admin/api/v1/users/supplierId/{supplierId}": {
    get: operations["getUsersBySupplierId"];
  };
  "/admreg/admin/api/v1/users/{id}": {
    get: operations["getUser"];
    put: operations["updateUser"];
    delete: operations["deleteUser"];
  };
  "/admreg/api/v1/isocategories": {
    get: operations["getAllCategories_1"];
  };
  "/admreg/api/v1/isocategories/{isocode}": {
    get: operations["getCategoryByIsocode_1"];
  };
  "/admreg/api/v1/techlabels": {
    get: operations["fetchTechLabels"];
  };
  "/admreg/api/v1/techlabels/name/{name}": {
    get: operations["fetchTechLabelsByName"];
  };
  "/admreg/api/v1/techlabels/{isocode}": {
    get: operations["fetchTechLabelsByIsocode"];
  };
  "/admreg/keys": {
    get: operations["keys"];
  };
  "/admreg/loggedInUser": {
    get: operations["getLoggedInUser"];
  };
  "/admreg/login": {
    post: operations["login"];
  };
  "/admreg/logout": {
    get: operations["indexGet"];
    post: operations["index"];
  };
  "/admreg/vendor/api/v1/agreement/registrations": {
    get: operations["findAgreements_1"];
  };
  "/admreg/vendor/api/v1/media/product/files/{oid}": {
    post: operations["uploadFiles"];
  };
  "/admreg/vendor/api/v1/media/{oid}": {
    get: operations["getMediaList_1"];
  };
  "/admreg/vendor/api/v1/media/{oid}/{uri}": {
    delete: operations["deleteFile_1"];
  };
  "/admreg/vendor/api/v1/product/registrations": {
    get: operations["findProducts_1"];
    post: operations["createProduct_1"];
  };
  "/admreg/vendor/api/v1/product/registrations/draft": {
    post: operations["draftProduct_1"];
  };
  "/admreg/vendor/api/v1/product/registrations/draft/variant/{id}": {
    post: operations["createProductVariant_1"];
  };
  "/admreg/vendor/api/v1/product/registrations/draftWith": {
    post: operations["draftProductWith_1"];
  };
  "/admreg/vendor/api/v1/product/registrations/excel/export": {
    post: operations["createExport_1"];
  };
  "/admreg/vendor/api/v1/product/registrations/excel/export/supplier": {
    post: operations["createExportForAllSupplierProducts"];
  };
  "/admreg/vendor/api/v1/product/registrations/excel/import": {
    post: operations["importExcel_1"];
  };
  "/admreg/vendor/api/v1/product/registrations/excel/import-dryrun": {
    post: operations["importExcelDryrun_1"];
  };
  "/admreg/vendor/api/v1/product/registrations/series/group": {
    get: operations["findSeriesGroup_1"];
  };
  "/admreg/vendor/api/v1/product/registrations/series/grouped/{seriesId}": {
    get: operations["getProductSeriesWithVariants"];
    put: operations["updateProductSeriesWithVariants"];
  };
  "/admreg/vendor/api/v1/product/registrations/series/{seriesId}": {
    get: operations["findBySeriesIdAndSupplierId_1"];
  };
  "/admreg/vendor/api/v1/product/registrations/{id}": {
    get: operations["getProductById_1"];
    put: operations["updateProduct_1"];
    delete: operations["deleteProduct_1"];
  };
  "/admreg/vendor/api/v1/series": {
    get: operations["getSeries"];
  };
  "/admreg/vendor/api/v1/supplier/registrations": {
    get: operations["getById_1"];
    put: operations["updateSupplier_1"];
  };
  "/admreg/vendor/api/v1/users": {
    get: operations["getUsers_1"];
    put: operations["updateUser_1"];
  };
  "/admreg/vendor/api/v1/users/password": {
    put: operations["changePassword_1"];
  };
  "/admreg/vendor/api/v1/users/{userId}": {
    get: operations["getUserId"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    AdminInfo: {
      approvedBy?: string | null;
      note?: string | null;
      /** Format: date-time */
      approved?: string | null;
    };
    /** @enum {string} */
    AdminStatus: "PENDING" | "APPROVED" | "REJECTED";
    AgreementAttachment: {
      /** Format: uuid */
      id?: string | null;
      title?: string | null;
      media: components["schemas"]["MediaInfo"][];
      description?: string | null;
    };
    AgreementBasicInformationDto: {
      /** Format: uuid */
      id: string;
      title: string;
      reference: string;
    };
    AgreementData: {
      resume?: string | null;
      text?: string | null;
      identifier: string;
      attachments: components["schemas"]["AgreementAttachment"][];
      /** @deprecated */
      posts: components["schemas"]["AgreementPost"][];
      isoCategory: string[];
    };
    AgreementDraftWithDTO: {
      title: string;
      reference: string;
      /** Format: date-time */
      published: string;
      /** Format: date-time */
      expired: string;
    };
    AgreementInfo: {
      /** Format: uuid */
      id: string;
      identifier?: string | null;
      title?: string | null;
      /** Format: int32 */
      rank: number;
      /** Format: int32 */
      postNr: number;
      postIdentifier?: string | null;
      postTitle?: string | null;
      /** Format: uuid */
      postId?: string | null;
      refNr?: string | null;
      reference: string;
      /** Format: date-time */
      expired: string;
      /** Format: date-time */
      published?: string | null;
    };
    AgreementPost: {
      identifier: string;
      /** Format: uuid */
      id?: string | null;
      /** Format: int32 */
      nr: number;
      refNr?: string | null;
      title: string;
      description: string;
      /** Format: date-time */
      created: string;
    };
    AgreementRegistrationDTO: {
      /** Format: uuid */
      id: string;
      draftStatus: components["schemas"]["DraftStatus"];
      agreementStatus: components["schemas"]["AgreementStatus"];
      title: string;
      reference: string;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
      /** Format: date-time */
      published: string;
      /** Format: date-time */
      expired: string;
      createdByUser: string;
      updatedByUser: string;
      createdBy: string;
      updatedBy: string;
      agreementData: components["schemas"]["AgreementData"];
      delkontraktList: components["schemas"]["DelkontraktRegistrationDTO"][];
      /** Format: int64 */
      version?: number | null;
    };
    /** @enum {string} */
    AgreementStatus: "ACTIVE" | "INACTIVE" | "DELETED";
    Attributes: {
      manufacturer?: string | null;
      compatibleWidth?: components["schemas"]["CompatibleWith"] | null;
      keywords?: string[] | null;
      series?: string | null;
      shortdescription?: string | null;
      text?: string | null;
      url?: string | null;
      bestillingsordning?: boolean | null;
      digitalSoknad?: boolean | null;
      sortimentKategori?: string | null;
      pakrevdGodkjenningskurs?: components["schemas"]["PakrevdGodkjenningskurs"] | null;
      produkttype?: components["schemas"]["Produkttype"] | null;
      tenderId?: string | null;
      hasTender?: boolean | null;
    };
    BestillingsordningRegistrationDTO: {
      /** Format: uuid */
      id: string;
      hmsArtNr: string;
      navn: string;
      status: components["schemas"]["BestillingsordningStatus"];
      updatedByUser: string;
      createdByUser: string;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
      /** Format: date-time */
      deactivated?: string | null;
    };
    /** @enum {string} */
    BestillingsordningStatus: "ACTIVE" | "INACTIVE";
    ChangePasswordDTO: {
      oldPassword: string;
      newPassword: string;
    };
    CompatibleWith: {
      seriesIds: string[];
    };
    DelkontraktData: {
      title?: string | null;
      description?: string | null;
      /** Format: int32 */
      sortNr: number;
      refNr?: string | null;
    };
    DelkontraktRegistrationDTO: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      agreementId: string;
      identifier: string;
      delkontraktData: components["schemas"]["DelkontraktData"];
      createdBy: string;
      updatedBy: string;
      /** Format: date-time */
      updated: string;
    };
    /** @enum {string} */
    DraftStatus: "DRAFT" | "DONE";
    DraftVariantDTO: {
      articleName: string;
      supplierRef: string;
    };
    Information: {
      message: string;
      type: components["schemas"]["Type"];
    };
    IsoCategoryDTO: {
      isoCode: string;
      isoTitle: string;
      isoTitleShort?: string | null;
      isoText: string;
      isoTextShort?: string | null;
      isoTranslations?: components["schemas"]["IsoTranslationsDTO"] | null;
      /** Format: int32 */
      isoLevel: number;
      isActive: boolean;
      showTech: boolean;
      allowMulti: boolean;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
    };
    IsoCategoryRegistrationDTO: {
      isoCode: string;
      isoTitle: string;
      isoText: string;
      isoTextShort: string;
      isoTranslations: components["schemas"]["IsoTranslations"];
      /** Format: int32 */
      isoLevel: number;
      isActive: boolean;
      showTech: boolean;
      allowMulti: boolean;
      createdByUser: string;
      updatedByUser: string;
      createdBy: string;
      updatedBy: string;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
    };
    IsoTranslations: {
      titleEn?: string | null;
      textEn?: string | null;
    };
    IsoTranslationsDTO: {
      titleEn?: string | null;
      textEn?: string | null;
    };
    MediaDTO: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      oid: string;
      uri: string;
      sourceUri: string;
      filename?: string | null;
      type: components["schemas"]["MediaType"];
      /** Format: int64 */
      size: number;
      md5: string;
      status: string;
      source: components["schemas"]["MediaSourceType"];
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
    };
    MediaInfo: {
      sourceUri: string;
      filename?: string | null;
      uri: string;
      /** Format: int32 */
      priority: number;
      type: components["schemas"]["MediaType"];
      text?: string | null;
      source: components["schemas"]["MediaSourceType"];
      /** Format: date-time */
      updated: string;
    };
    /** @enum {string} */
    MediaSourceType: "HMDB" | "REGISTER" | "EXTERNALURL" | "IMPORT" | "UNKNOWN";
    /** @enum {string} */
    MediaType: "PDF" | "IMAGE" | "VIDEO" | "XLS" | "OTHER";
    NewsRegistrationDTO: {
      /** Format: uuid */
      id: string;
      title: string;
      text: string;
      status: components["schemas"]["NewsStatus"];
      draftStatus: components["schemas"]["DraftStatus"];
      /** Format: date-time */
      published: string;
      /** Format: date-time */
      expired: string;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
      author: string;
      createdBy: string;
      updatedBy: string;
      createdByUser: string;
      updatedByUser: string;
    };
    /** @enum {string} */
    NewsStatus: "ACTIVE" | "INACTIVE" | "DELETED";
    OpenApiPageable: {
      /**
       * Format: int32
       * @description page number
       * @example 0
       */
      number: number;
      /**
       * Format: int32
       * @description Page size
       * @example 100
       */
      size: number;
      /**
       * @description Sort
       * @example updated,desc
       */
      sort: string;
    };
    Page_AgreementBasicInformationDto_: components["schemas"]["Slice_AgreementBasicInformationDto_"] & {
      /** Format: int64 */
      totalSize: number;
      /** Format: int32 */
      totalPages?: number;
    };
    Page_NewsRegistrationDTO_: components["schemas"]["Slice_NewsRegistrationDTO_"] & {
      /** Format: int64 */
      totalSize: number;
      /** Format: int32 */
      totalPages?: number;
    };
    Page_ProductRegistrationDTO_: components["schemas"]["Slice_ProductRegistrationDTO_"] & {
      /** Format: int64 */
      totalSize: number;
      /** Format: int32 */
      totalPages?: number;
    };
    Page_ProductToApproveDto_: components["schemas"]["Slice_ProductToApproveDto_"] & {
      /** Format: int64 */
      totalSize: number;
      /** Format: int32 */
      totalPages?: number;
    };
    Page_SeriesRegistrationDTO_: components["schemas"]["Slice_SeriesRegistrationDTO_"] & {
      /** Format: int64 */
      totalSize: number;
      /** Format: int32 */
      totalPages?: number;
    };
    Page_SupplierRegistrationDTO_: components["schemas"]["Slice_SupplierRegistrationDTO_"] & {
      /** Format: int64 */
      totalSize: number;
      /** Format: int32 */
      totalPages?: number;
    };
    Page_UserDTO_: components["schemas"]["Slice_UserDTO_"] & {
      /** Format: int64 */
      totalSize: number;
      /** Format: int32 */
      totalPages?: number;
    };
    "Pair_ProductAgreementRegistrationDTO.List_Information__": {
      first: components["schemas"]["ProductAgreementRegistrationDTO"];
      second: components["schemas"]["Information"][];
    };
    PakrevdGodkjenningskurs: {
      tittel: string;
      isokode: string;
      /** Format: int32 */
      kursId: number;
    };
    ProductAgreementDeletedResponse: {
      /** Format: uuid */
      id: string;
    };
    ProductAgreementImportDTO: {
      dryRun: boolean;
      /** Format: int32 */
      count: number;
      productAgreements: components["schemas"]["ProductAgreementRegistrationDTO"][];
      productAgreementsWithInformation: components["schemas"]["Pair_ProductAgreementRegistrationDTO.List_Information__"][];
    };
    ProductAgreementRegistrationDTO: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      productId?: string | null;
      /** Format: uuid */
      seriesUuid?: string | null;
      title: string;
      articleName?: string | null;
      /** Format: uuid */
      supplierId: string;
      supplierRef: string;
      hmsArtNr?: string | null;
      /** Format: uuid */
      agreementId: string;
      reference: string;
      /** Format: int32 */
      post: number;
      /** Format: int32 */
      rank: number;
      /** Format: uuid */
      postId?: string | null;
      status: components["schemas"]["ProductAgreementStatus"];
      createdBy: string;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
      /** Format: date-time */
      published: string;
      /** Format: date-time */
      expired: string;
      updatedByUser: string;
    };
    /** @enum {string} */
    ProductAgreementStatus: "ACTIVE" | "INACTIVE" | "DELETED";
    ProductAgreementsDeletedResponse: {
      ids: string[];
    };
    ProductData: {
      attributes: components["schemas"]["Attributes"];
      accessory: boolean;
      sparePart: boolean;
      techData: components["schemas"]["TechData"][];
      media: components["schemas"]["MediaInfo"][];
      identifier?: string | null;
      seriesIdentifier?: string | null;
    };
    ProductDraftWithDTO: {
      title: string;
      text: string;
      isoCategory: string;
    };
    ProductRegistrationDTO: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      supplierId: string;
      supplierRef: string;
      hmsArtNr?: string | null;
      /** Format: uuid */
      seriesUUID?: string | null;
      /** @deprecated */
      seriesId: string;
      isoCategory: string;
      title: string;
      articleName: string;
      draftStatus: components["schemas"]["DraftStatus"];
      adminStatus: components["schemas"]["AdminStatus"];
      registrationStatus: components["schemas"]["RegistrationStatus"];
      message?: string | null;
      adminInfo?: components["schemas"]["AdminInfo"] | null;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
      /** Format: date-time */
      published?: string | null;
      /** Format: date-time */
      expired?: string | null;
      updatedByUser: string;
      createdByUser: string;
      createdBy: string;
      updatedBy: string;
      createdByAdmin: boolean;
      productData: components["schemas"]["ProductData"];
      agreements: components["schemas"]["AgreementInfo"][];
      /** Format: int64 */
      version?: number | null;
    };
    ProductRegistrationDryRunDTO: {
      /** Format: uuid */
      id?: string | null;
      /** Format: uuid */
      supplierId: string;
      supplierRef: string;
      hmsArtNr?: string | null;
      /** Format: uuid */
      seriesUUID?: string | null;
      isoCategory: string;
      title: string;
      articleName: string;
      draftStatus: components["schemas"]["DraftStatus"];
      adminStatus: components["schemas"]["AdminStatus"];
      registrationStatus: components["schemas"]["RegistrationStatus"];
      message?: string | null;
      adminInfo?: components["schemas"]["AdminInfo"] | null;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
      /** Format: date-time */
      published?: string | null;
      /** Format: date-time */
      expired?: string | null;
      updatedByUser: string;
      createdByUser: string;
      createdBy: string;
      updatedBy: string;
      createdByAdmin: boolean;
      productData: components["schemas"]["ProductData"];
      agreements: components["schemas"]["AgreementInfo"][];
      /** Format: int64 */
      version?: number | null;
    };
    ProductSeriesWithVariantsDTO: {
      /** Format: uuid */
      id: string;
      adminStatus: components["schemas"]["AdminStatus"];
      /** Format: date-time */
      created: string;
      createdBy: string;
      createdByAdmin: boolean;
      createdByUser: string;
      draftStatus: components["schemas"]["DraftStatus"];
      /** Format: date-time */
      expired?: string | null;
      isoCategory: string;
      productData: components["schemas"]["ProductData"];
      /** Format: date-time */
      published?: string | null;
      registrationStatus: components["schemas"]["RegistrationStatus"];
      /** Format: uuid */
      seriesUUID?: string | null;
      seriesId: string;
      /** Format: uuid */
      supplierId: string;
      title: string;
      /** Format: date-time */
      updated: string;
      updatedBy: string;
      updatedByUser: string;
      variants: components["schemas"]["ProductRegistrationDTO"][];
    };
    ProductToApproveDto: {
      title: string;
      /** Format: uuid */
      seriesId: string;
      status: string;
      supplierName: string;
      /** Format: uuid */
      agreementId?: string | null;
      delkontrakttittel?: string | null;
    };
    ProductVariantsForDelkontraktDto: {
      /** Format: uuid */
      postId: string;
      /** Format: uuid */
      productSeries?: string | null;
      productTitle: string;
      serieIdentifier?: string | null;
      /** Format: int32 */
      rank: number;
      productVariants: components["schemas"]["ProductAgreementRegistrationDTO"][];
    };
    /** @enum {string} */
    Produkttype: "Hovedprodukt" | "Tilbehoer" | "Del";
    ProduktvarianterForDelkontrakterDTO: {
      /** Format: int32 */
      delkontraktNr: number;
      produktTittel: string;
      /** Format: int32 */
      rangering: number;
      /** Format: uuid */
      produktserie?: string | null;
      serieIdentifier?: string | null;
      produktvarianter: components["schemas"]["ProductAgreementRegistrationDTO"][];
    };
    RegistrationAuthentication: {
      name: string;
      attributes: {
        [key: string]: unknown;
      };
    };
    /** @enum {string} */
    RegistrationStatus: "ACTIVE" | "INACTIVE" | "DELETED";
    SeriesGroupDTO: {
      title: string;
      seriesId: string;
      /** Format: int64 */
      count: number;
    };
    SeriesRegistrationDTO: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      supplierId: string;
      identifier: string;
      title: string;
      text: string;
      isoCategory: string;
      draftStatus: components["schemas"]["DraftStatus"];
      status: components["schemas"]["SeriesStatus"];
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
      /** Format: date-time */
      expired: string;
      createdBy: string;
      updatedBy: string;
      updatedByUser: string;
      createdByUser: string;
      createdByAdmin: boolean;
      /** Format: int64 */
      version?: number | null;
    };
    /** @enum {string} */
    SeriesStatus: "ACTIVE" | "INACTIVE" | "PENDING" | "REJECTED";
    Slice_AgreementBasicInformationDto_: {
      content: components["schemas"]["AgreementBasicInformationDto"][];
      pageable: components["schemas"]["OpenApiPageable"];
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int64 */
      offset?: number;
      /** Format: int32 */
      size?: number;
      empty?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
    };
    Slice_NewsRegistrationDTO_: {
      content: components["schemas"]["NewsRegistrationDTO"][];
      pageable: components["schemas"]["OpenApiPageable"];
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int64 */
      offset?: number;
      /** Format: int32 */
      size?: number;
      empty?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
    };
    Slice_ProductRegistrationDTO_: {
      content: components["schemas"]["ProductRegistrationDTO"][];
      pageable: components["schemas"]["OpenApiPageable"];
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int64 */
      offset?: number;
      /** Format: int32 */
      size?: number;
      empty?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
    };
    Slice_ProductToApproveDto_: {
      content: components["schemas"]["ProductToApproveDto"][];
      pageable: components["schemas"]["OpenApiPageable"];
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int64 */
      offset?: number;
      /** Format: int32 */
      size?: number;
      empty?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
    };
    Slice_SeriesRegistrationDTO_: {
      content: components["schemas"]["SeriesRegistrationDTO"][];
      pageable: components["schemas"]["OpenApiPageable"];
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int64 */
      offset?: number;
      /** Format: int32 */
      size?: number;
      empty?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
    };
    Slice_SupplierRegistrationDTO_: {
      content: components["schemas"]["SupplierRegistrationDTO"][];
      pageable: components["schemas"]["OpenApiPageable"];
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int64 */
      offset?: number;
      /** Format: int32 */
      size?: number;
      empty?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
    };
    Slice_UserDTO_: {
      content: components["schemas"]["UserDTO"][];
      pageable: components["schemas"]["OpenApiPageable"];
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int64 */
      offset?: number;
      /** Format: int32 */
      size?: number;
      empty?: boolean;
      /** Format: int32 */
      numberOfElements?: number;
    };
    SupplierData: {
      address?: string | null;
      postNr?: string | null;
      postLocation?: string | null;
      countryCode?: string | null;
      email?: string | null;
      phone?: string | null;
      homepage?: string | null;
    };
    SupplierRegistrationDTO: {
      /** Format: uuid */
      id: string;
      status: components["schemas"]["SupplierStatus"];
      draftStatus: components["schemas"]["DraftStatus"];
      name: string;
      supplierData: components["schemas"]["SupplierData"];
      identifier: string;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
      createdBy: string;
      updatedBy: string;
      updatedByUser: string;
      createdByUser: string;
    };
    /** @enum {string} */
    SupplierStatus: "INACTIVE" | "ACTIVE";
    TechData: {
      key: string;
      value: string;
      unit: string;
    };
    TechLabelDTO: {
      /** Format: uuid */
      id: string;
      identifier: string;
      label: string;
      guide: string;
      definition?: string | null;
      isocode: string;
      type: string;
      unit?: string | null;
      /** Format: int32 */
      sort: number;
      createdBy: string;
      updatedBy: string;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
    };
    TechLabelRegistrationDTO: {
      /** Format: uuid */
      id: string;
      identifier: string;
      label: string;
      guide: string;
      definition?: string | null;
      isoCode: string;
      type: string;
      unit?: string | null;
      /** Format: int32 */
      sort: number;
      isActive: boolean;
      createdBy: string;
      updatedBy: string;
      updatedByUser: string;
      createdByUser: string;
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
    };
    /** @enum {string} */
    Type: "INFO" | "WARNING";
    Unit: Record<string, never>;
    UserDTO: {
      /** Format: uuid */
      id: string;
      name: string;
      email: string;
      roles: string[];
      attributes: {
        [key: string]: string;
      };
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      updated: string;
    };
    UserRegistrationDTO: {
      /** Format: uuid */
      id: string;
      name: string;
      email: string;
      password: string;
      roles: string[];
      attributes: {
        [key: string]: string;
      };
    };
    UsernamePasswordCredentials: {
      username: string | null;
      password: string | null;
      identity?: string | null;
      secret?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  createDelkontrakt: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DelkontraktRegistrationDTO"];
      };
    };
    responses: {
      /** @description createDelkontrakt 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["DelkontraktRegistrationDTO"];
        };
      };
    };
  };
  findByAgreementId: {
    parameters: {
      path: {
        agreementId: string;
      };
    };
    responses: {
      /** @description findByAgreementId 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["DelkontraktRegistrationDTO"][];
        };
      };
    };
  };
  findByDelkontraktId: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description findByDelkontraktId 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["DelkontraktRegistrationDTO"];
        };
      };
    };
  };
  updateDelkontrakt: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DelkontraktRegistrationDTO"];
      };
    };
    responses: {
      /** @description updateDelkontrakt 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["DelkontraktRegistrationDTO"];
        };
      };
    };
  };
  deleteDelkontraktById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description deleteDelkontraktById 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Unit"];
        };
      };
    };
  };
  findAgreements: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description findAgreements 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_AgreementBasicInformationDto_"];
        };
      };
    };
  };
  createAgreement: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgreementRegistrationDTO"];
      };
    };
    responses: {
      /** @description createAgreement 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["AgreementRegistrationDTO"];
        };
      };
    };
  };
  createAgreementFromAnother: {
    parameters: {
      path: {
        id: string;
        reference: string;
      };
    };
    responses: {
      /** @description createAgreementFromAnother 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["AgreementRegistrationDTO"];
        };
      };
    };
  };
  draftAgreementWith: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgreementDraftWithDTO"];
      };
    };
    responses: {
      /** @description draftAgreementWith 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["AgreementRegistrationDTO"];
        };
      };
    };
  };
  draftAgreement: {
    parameters: {
      path: {
        reference: string;
      };
    };
    responses: {
      /** @description draftAgreement 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["AgreementRegistrationDTO"];
        };
      };
    };
  };
  getAgreementById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description getAgreementById 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["AgreementRegistrationDTO"];
        };
      };
    };
  };
  updateAgreement: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AgreementRegistrationDTO"];
      };
    };
    responses: {
      /** @description updateAgreement 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["AgreementRegistrationDTO"];
        };
      };
    };
  };
  deleteAgreement: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description deleteAgreement 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["AgreementRegistrationDTO"];
        };
      };
    };
  };
  getDelkontraktById: {
    parameters: {
      path: {
        id: string;
        delkontraktId: string;
      };
    };
    responses: {
      /** @description getDelkontraktById 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["AgreementPost"];
        };
      };
    };
  };
  deleteDelkontraktById_1: {
    parameters: {
      path: {
        id: string;
        delkontraktId: string;
      };
    };
    responses: {
      /** @description deleteDelkontraktById_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["AgreementRegistrationDTO"];
        };
      };
    };
  };
  createBestillingsordning: {
    requestBody: {
      content: {
        "application/json": {
          dto: components["schemas"]["BestillingsordningRegistrationDTO"];
        };
      };
    };
    responses: {
      /** @description createBestillingsordning 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["BestillingsordningRegistrationDTO"];
        };
      };
    };
  };
  findByHmsNr: {
    parameters: {
      path: {
        hmsArtNr: string;
      };
    };
    responses: {
      /** @description findByHmsNr 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["BestillingsordningRegistrationDTO"];
        };
      };
    };
  };
  updateBestillingsordningStatus: {
    requestBody: {
      content: {
        "application/json": {
          dto: components["schemas"]["BestillingsordningRegistrationDTO"];
        };
      };
    };
    responses: {
      /** @description updateBestillingsordningStatus 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["BestillingsordningRegistrationDTO"];
        };
      };
    };
  };
  createSupplierToken: {
    parameters: {
      path: {
        supplierId: string;
      };
    };
    responses: {
      /** @description createSupplierToken 200 response */
      200: {
        content: {
          "application/json": string;
        };
      };
    };
  };
  getAllCategories: {
    responses: {
      /** @description getAllCategories 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["IsoCategoryRegistrationDTO"][];
        };
      };
    };
  };
  createIsoCategory: {
    requestBody: {
      content: {
        "application/json": {
          dto: components["schemas"]["IsoCategoryRegistrationDTO"];
        };
      };
    };
    responses: {
      /** @description createIsoCategory 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["IsoCategoryRegistrationDTO"];
        };
      };
    };
  };
  getCategoryByIsocode: {
    parameters: {
      path: {
        isocode: string;
      };
    };
    responses: {
      /** @description getCategoryByIsocode 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["IsoCategoryRegistrationDTO"];
        };
      };
    };
  };
  updateCategoryByIsocode: {
    parameters: {
      path: {
        isocode: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          dto: components["schemas"]["IsoCategoryRegistrationDTO"];
        };
      };
    };
    responses: {
      /** @description updateCategoryByIsocode 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["IsoCategoryRegistrationDTO"];
        };
      };
    };
  };
  uploadAgreementFiles: {
    parameters: {
      path: {
        oid: string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          files: string[];
        };
      };
    };
    responses: {
      /** @description uploadAgreementFiles 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaDTO"][];
        };
      };
    };
  };
  uploadProductFiles: {
    parameters: {
      path: {
        oid: string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          files: string[];
        };
      };
    };
    responses: {
      /** @description uploadProductFiles 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaDTO"][];
        };
      };
    };
  };
  getMediaList: {
    parameters: {
      path: {
        oid: string;
      };
    };
    responses: {
      /** @description getMediaList 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaDTO"][];
        };
      };
    };
  };
  deleteFile: {
    parameters: {
      path: {
        oid: string;
        uri: string;
      };
    };
    responses: {
      /** @description deleteFile 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaDTO"];
        };
      };
    };
  };
  getNews: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description getNews 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_NewsRegistrationDTO_"];
        };
      };
    };
  };
  createNews: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewsRegistrationDTO"];
      };
    };
    responses: {
      /** @description createNews 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["NewsRegistrationDTO"];
        };
      };
    };
  };
  createNewsDraft: {
    responses: {
      /** @description createNewsDraft 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["NewsRegistrationDTO"];
        };
      };
    };
  };
  updateNews: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewsRegistrationDTO"];
      };
    };
    responses: {
      /** @description updateNews 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["NewsRegistrationDTO"];
        };
      };
    };
  };
  deleteNews: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description deleteNews 200 response */
      200: {
        content: never;
      };
    };
  };
  createProductAgreement: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["ProductAgreementRegistrationDTO"];
      };
    };
    responses: {
      /** @description createProductAgreement 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductAgreementRegistrationDTO"];
        };
      };
    };
  };
  updateProductAgreements: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductAgreementRegistrationDTO"][];
      };
    };
    responses: {
      /** @description updateProductAgreements 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductAgreementRegistrationDTO"][];
        };
      };
    };
  };
  createProductAgreements: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductAgreementRegistrationDTO"][];
      };
    };
    responses: {
      /** @description createProductAgreements 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductAgreementRegistrationDTO"][];
        };
      };
    };
  };
  excelImport: {
    parameters: {
      query: {
        dryRun: boolean;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description excelImport 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductAgreementImportDTO"];
        };
      };
    };
  };
  getProductsAgreementsByIds: {
    requestBody: {
      content: {
        "application/json": string[];
      };
    };
    responses: {
      /** @description getProductsAgreementsByIds 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductAgreementRegistrationDTO"][];
        };
      };
    };
  };
  deleteProductAgreementByIds: {
    requestBody: {
      content: {
        "application/json": string[];
      };
    };
    responses: {
      /** @description deleteProductAgreementByIds 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductAgreementsDeletedResponse"];
        };
      };
    };
  };
  getProductVariantsByDelkontraktId: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description getProductVariantsByDelkontraktId 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductVariantsForDelkontraktDto"][];
        };
      };
    };
  };
  getProductVariantsByAgreementId: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description getProductVariantsByAgreementId 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProduktvarianterForDelkontrakterDTO"][];
        };
      };
    };
  };
  getProductsByAgreementId: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description getProductsByAgreementId 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductAgreementRegistrationDTO"][];
        };
      };
    };
  };
  deleteProductAgreementById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description deleteProductAgreementById 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductAgreementDeletedResponse"];
        };
      };
    };
  };
  findProducts: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description findProducts 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_ProductRegistrationDTO_"];
        };
      };
    };
  };
  createProduct: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductRegistrationDTO"];
      };
    };
    responses: {
      /** @description createProduct 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  approveProduct: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description approveProduct 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  draftProduct: {
    parameters: {
      query: {
        isAccessory: boolean;
        isSparePart: boolean;
      };
      path: {
        supplierId: string;
      };
    };
    responses: {
      /** @description draftProduct 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  createProductVariant: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DraftVariantDTO"];
      };
    };
    responses: {
      /** @description createProductVariant 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  draftProductWith: {
    parameters: {
      query: {
        isAccessory: boolean;
        isSparePart: boolean;
      };
      path: {
        supplierId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductDraftWithDTO"];
      };
    };
    responses: {
      /** @description draftProductWith 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  createExport: {
    requestBody: {
      content: {
        "application/json": string[];
      };
    };
    responses: {
      /** @description createExport 200 response */
      200: {
        content: {
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
        };
      };
    };
  };
  importExcel: {
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description importExcel 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"][];
        };
      };
    };
  };
  importExcelDryrun: {
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description importExcelDryrun 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDryRunDTO"][];
        };
      };
    };
  };
  getProductByHmsArtNr: {
    parameters: {
      path: {
        hmsArtNr: string;
      };
    };
    responses: {
      /** @description getProductByHmsArtNr 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  findSeriesGroup: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description findSeriesGroup 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["SeriesGroupDTO"][];
        };
      };
    };
  };
  findBySeriesIdAndSupplierId: {
    parameters: {
      path: {
        seriesId: string;
      };
    };
    responses: {
      /** @description findBySeriesIdAndSupplierId 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"][];
        };
      };
    };
  };
  findProductsPendingApprove: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description findProductsPendingApprove 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_ProductToApproveDto_"];
        };
      };
    };
  };
  getProductById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description getProductById 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  updateProduct: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductRegistrationDTO"];
      };
    };
    responses: {
      /** @description updateProduct 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  deleteProduct: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description deleteProduct 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  findSuppliers: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description findSuppliers 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_SupplierRegistrationDTO_"];
        };
      };
    };
  };
  createSupplier: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupplierRegistrationDTO"];
      };
    };
    responses: {
      /** @description createSupplier 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["SupplierRegistrationDTO"];
        };
      };
    };
  };
  getById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description getById 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["SupplierRegistrationDTO"];
        };
      };
    };
  };
  updateSupplier: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupplierRegistrationDTO"];
      };
    };
    responses: {
      /** @description updateSupplier 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["SupplierRegistrationDTO"];
        };
      };
    };
  };
  deactivateSupplier: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description deactivateSupplier 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["SupplierRegistrationDTO"];
        };
      };
    };
  };
  getAllTechLabels: {
    responses: {
      /** @description getAllTechLabels 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["TechLabelRegistrationDTO"][];
        };
      };
    };
  };
  createTechLabel: {
    requestBody: {
      content: {
        "application/json": {
          dto: components["schemas"]["TechLabelRegistrationDTO"];
        };
      };
    };
    responses: {
      /** @description createTechLabel 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["TechLabelRegistrationDTO"];
        };
      };
    };
  };
  getTechLabelById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description getTechLabelById 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["TechLabelRegistrationDTO"];
        };
      };
    };
  };
  updateTechLabel: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": {
          dto: components["schemas"]["TechLabelRegistrationDTO"];
        };
      };
    };
    responses: {
      /** @description updateTechLabel 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["TechLabelRegistrationDTO"];
        };
      };
    };
  };
  getUsers: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description getUsers 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_UserDTO_"];
        };
      };
    };
  };
  createUser: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserRegistrationDTO"];
      };
    };
    responses: {
      /** @description createUser 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["UserDTO"];
        };
      };
    };
  };
  getUserByEmail: {
    parameters: {
      path: {
        email: string;
      };
    };
    responses: {
      /** @description getUserByEmail 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["UserDTO"];
        };
      };
    };
  };
  changePassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordDTO"];
      };
    };
    responses: {
      /** @description changePassword 200 response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  getUsersBySupplierId: {
    parameters: {
      path: {
        supplierId: string;
      };
    };
    responses: {
      /** @description getUsersBySupplierId 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["UserDTO"][];
        };
      };
    };
  };
  getUser: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description getUser 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["UserDTO"];
        };
      };
    };
  };
  updateUser: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserDTO"];
      };
    };
    responses: {
      /** @description updateUser 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["UserDTO"];
        };
      };
    };
  };
  deleteUser: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description deleteUser 200 response */
      200: {
        content: {
          "application/json": string;
        };
      };
    };
  };
  getAllCategories_1: {
    responses: {
      /** @description getAllCategories_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["IsoCategoryDTO"][];
        };
      };
    };
  };
  getCategoryByIsocode_1: {
    parameters: {
      path: {
        isocode: string;
      };
    };
    responses: {
      /** @description getCategoryByIsocode_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["IsoCategoryDTO"];
        };
      };
    };
  };
  fetchTechLabels: {
    responses: {
      /** @description fetchTechLabels 200 response */
      200: {
        content: {
          "application/json": {
            [key: string]: components["schemas"]["TechLabelDTO"][];
          };
        };
      };
    };
  };
  fetchTechLabelsByName: {
    parameters: {
      path: {
        name: string;
      };
    };
    responses: {
      /** @description fetchTechLabelsByName 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["TechLabelDTO"][];
        };
      };
    };
  };
  fetchTechLabelsByIsocode: {
    parameters: {
      path: {
        isocode: string;
      };
    };
    responses: {
      /** @description fetchTechLabelsByIsocode 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["TechLabelDTO"][];
        };
      };
    };
  };
  keys: {
    responses: {
      /** @description keys 200 response */
      200: {
        content: {
          "application/json": string[];
        };
      };
    };
  };
  getLoggedInUser: {
    responses: {
      /** @description getLoggedInUser 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["RegistrationAuthentication"];
        };
      };
    };
  };
  login: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["UsernamePasswordCredentials"];
        "application/json": components["schemas"]["UsernamePasswordCredentials"];
      };
    };
    responses: {
      /** @description login 200 response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  indexGet: {
    responses: {
      /** @description indexGet 200 response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  index: {
    responses: {
      /** @description index 200 response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  findAgreements_1: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description findAgreements_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_AgreementBasicInformationDto_"];
        };
      };
    };
  };
  uploadFiles: {
    parameters: {
      path: {
        oid: string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          files: string[];
        };
      };
    };
    responses: {
      /** @description uploadFiles 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaDTO"][];
        };
      };
    };
  };
  getMediaList_1: {
    parameters: {
      path: {
        oid: string;
      };
    };
    responses: {
      /** @description getMediaList_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaDTO"][];
        };
      };
    };
  };
  deleteFile_1: {
    parameters: {
      path: {
        oid: string;
        uri: string;
      };
    };
    responses: {
      /** @description deleteFile_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["MediaDTO"];
        };
      };
    };
  };
  findProducts_1: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description findProducts_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_ProductRegistrationDTO_"];
        };
      };
    };
  };
  createProduct_1: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductRegistrationDTO"];
      };
    };
    responses: {
      /** @description createProduct_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  draftProduct_1: {
    parameters: {
      query: {
        isAccessory: boolean;
        isSparePart: boolean;
      };
    };
    responses: {
      /** @description draftProduct_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  createProductVariant_1: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DraftVariantDTO"];
      };
    };
    responses: {
      /** @description createProductVariant_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  draftProductWith_1: {
    parameters: {
      query: {
        isAccessory: boolean;
        isSparePart: boolean;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductDraftWithDTO"];
      };
    };
    responses: {
      /** @description draftProductWith_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  createExport_1: {
    requestBody: {
      content: {
        "application/json": string[];
      };
    };
    responses: {
      /** @description createExport_1 200 response */
      200: {
        content: {
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
        };
      };
    };
  };
  createExportForAllSupplierProducts: {
    responses: {
      /** @description createExportForAllSupplierProducts 200 response */
      200: {
        content: {
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
        };
      };
    };
  };
  importExcel_1: {
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description importExcel_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"][];
        };
      };
    };
  };
  importExcelDryrun_1: {
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description importExcelDryrun_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDryRunDTO"][];
        };
      };
    };
  };
  findSeriesGroup_1: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description findSeriesGroup_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["SeriesGroupDTO"][];
        };
      };
    };
  };
  getProductSeriesWithVariants: {
    parameters: {
      path: {
        seriesId: string;
      };
    };
    responses: {
      /** @description getProductSeriesWithVariants 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductSeriesWithVariantsDTO"];
        };
      };
    };
  };
  updateProductSeriesWithVariants: {
    parameters: {
      path: {
        seriesId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductSeriesWithVariantsDTO"];
      };
    };
    responses: {
      /** @description updateProductSeriesWithVariants 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  findBySeriesIdAndSupplierId_1: {
    parameters: {
      path: {
        seriesId: string;
      };
    };
    responses: {
      /** @description findBySeriesIdAndSupplierId_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"][];
        };
      };
    };
  };
  getProductById_1: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description getProductById_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  updateProduct_1: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductRegistrationDTO"];
      };
    };
    responses: {
      /** @description updateProduct_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  deleteProduct_1: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description deleteProduct_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["ProductRegistrationDTO"];
        };
      };
    };
  };
  getSeries: {
    parameters: {
      query: {
        params?: {
          [key: string]: string;
        } | null;
        pageable: components["schemas"]["OpenApiPageable"];
      };
    };
    responses: {
      /** @description getSeries 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["Page_SeriesRegistrationDTO_"];
        };
      };
    };
  };
  getById_1: {
    responses: {
      /** @description getById_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["SupplierRegistrationDTO"];
        };
      };
    };
  };
  updateSupplier_1: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupplierRegistrationDTO"];
      };
    };
    responses: {
      /** @description updateSupplier_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["SupplierRegistrationDTO"];
        };
      };
    };
  };
  getUsers_1: {
    responses: {
      /** @description getUsers_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["UserDTO"][];
        };
      };
    };
  };
  updateUser_1: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserDTO"];
      };
    };
    responses: {
      /** @description updateUser_1 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["UserDTO"];
        };
      };
    };
  };
  changePassword_1: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordDTO"];
      };
    };
    responses: {
      /** @description changePassword_1 200 response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  getUserId: {
    parameters: {
      path: {
        userId: string;
      };
    };
    responses: {
      /** @description getUserId 200 response */
      200: {
        content: {
          "application/json": components["schemas"]["UserDTO"];
        };
      };
    };
  };
}
