import { components } from './schema' // <- generated by openapi-typescript

// Schema Obj
export type UserDTO = components['schemas']['UserDTO']
export type AdminUserChunk = components['schemas']['Page_UserDTO_']
export type SupplierRegistrationDTO = components['schemas']['SupplierRegistrationDTO']
export type UserRegistrationDTO = components['schemas']['UserRegistrationDTO']
export type LoggedInUserResponse = components['schemas']['Authentication']
export type SupplierStatus = components['schemas']['SupplierStatus']
export type DraftStatus = components['schemas']['DraftStatus']
export type SupplierChunk = components['schemas']['Page_SupplierRegistrationDTO_']
export type SupplierUserChunk = components['schemas']['Page_UserDTO_']
export type SeriesChunk = {
  content: components['schemas']['SeriesGroupDTO'][]
  pageable: components['schemas']['OpenApiPageable']
  /** Format: int32 */
  pageNumber?: number
  /** Format: int64 */
  offset?: number
  /** Format: int32 */
  size?: number
  empty?: boolean
  /** Format: int32 */
  numberOfElements?: number
}
export type AgreementsChunk = {
  content: components['schemas']['AgreementBasicInformationDto'][]
  pageable: components['schemas']['OpenApiPageable']
  /** Format: int32 */
  pageNumber?: number
  /** Format: int64 */
  offset?: number
  /** Format: int32 */
  size?: number
  totalPages?: number
  empty?: boolean
  /** Format: int32 */
  numberOfElements?: number
}
export type SeriesGroupDTO = components['schemas']['SeriesGroupDTO'][]
export type ProductRegistrationDTO = components['schemas']['ProductRegistrationDTO']
export type AgreementRegistrationDTO = components['schemas']['AgreementRegistrationDTO']
export type AgreementPostDTO = components['schemas']['AgreementPost']
export type IsoCategoryDTO = components['schemas']['IsoCategoryDTO']
export type AgreementGroupDto = components['schemas']['AgreementBasicInformationDto'][]
export type AgreementAttachment = components['schemas']['AgreementAttachment']
export type AgreementDraftWithDTO = components['schemas']['AgreementDraftWithDTO']
export type MediaDTO = components['schemas']['MediaDTO']
export type MediaInfo = components['schemas']['MediaInfo']
export type ProductDraftWithDTO = components['schemas']['ProductDraftWithDTO']
export type DraftVariantDTO = components['schemas']['DraftVariantDTO']
export type TechData = components['schemas']['TechData']

// Path params
//type EndpointParams = paths['/my/endpoint']['parameters']

// Response obj
//type SuccessResponse = paths['/my/endpoint']['get']['responses'][200]['content']['application/json']['schema']
//type ErrorResponse = paths['/my/endpoint']['get']['responses'][500]['content']['application/json']['schema']
