name: Bygg og deploy til dev og prod

on:
  push:
    branches:
      - main

run-name: Bygg og deploy til dev og prod

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          cache: npm

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Build before tests
        run: npm run build

      - name: Run tests
        run: npm test

  build:
    needs: [test]
    name: Build and push docker container
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build.outputs.image }}
    steps:
      - uses: actions/checkout@v5
      - uses: nais/docker-build-push@v0
        id: docker-build
        with:
          team: teamdigihot
          build_args: |
            BUILD_ENV=${{ env.BUILD_ENV }}
            CLUSTER=${{ env.CLUSTER }}
          build_secrets: |
            "NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}"
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  deploy-dev:
    name: Deploy dev
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yaml
          VAR: image=${{ needs.build.outputs.image }}
          VARS: .nais/nais-dev.json

  deploy-prod:
    name: Deploy prod
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml
          VAR: image=${{ needs.build.outputs.image }}
          VARS: .nais/nais-prod.json
